[Pallet] integrate fund.rs.
Remove test code because access storage not acceptable in test.

ex.
```
thread 'fund::tests::test_try_unlock_zero' panicked at '`get_version_1` called outside of an Externalities-provided environment.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/83544d4/primitives/io/src/lib.rs:79:1
```